include /etc/nginx/conf.d/upstream.inc; #backend 쪽으로 트래픽을 보내서 포워딩을 해준다 리버스 프록시의 역활

server {
    listen 80;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
    }
}